# Generated by Django 4.2.14 on 2024-07-26 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_homework_difficulty_alter_homework_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='note',
            field=models.TextField(default=''),
        ),
    ]
